import 'package:app_v2/models/2.%20team_model.dart';

import 'models/1. player_model.dart';
import 'models/3. league_model.dart';

const DUMMY_PLAYERS = [
  PlayerModel(playerId: 1, playerName: "Player 1", playerTeamName: "Team 1"),
  PlayerModel(playerId: 2, playerName: "Player 2", playerTeamName: "Team 2"),
  PlayerModel(playerId: 3, playerName: "Player 3", playerTeamName: "Team 3"),
  PlayerModel(playerId: 4, playerName: "Player 4", playerTeamName: "Team 4"),
];

final List<TeamModel> DUMMY_TEAMS = [
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 2,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 3,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 4,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 5,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 6,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 7,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 8,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 9,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 10,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 11,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 8,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 9,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 10,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 11,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 9,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 10,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 4,
  ),
  const TeamModel(
    teamId: 11,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 4,
  ),
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 2,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 3,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 4,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 5,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 6,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 7,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 8,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 9,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 10,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 11,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 8,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 9,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 10,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 11,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 9,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 10,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 4,
  ),
  const TeamModel(
    teamId: 11,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 4,
  ),
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 2,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 3,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 4,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 5,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 6,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 7,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 8,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 9,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 10,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 11,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 8,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 9,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 10,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 11,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 9,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 10,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 4,
  ),
  const TeamModel(
    teamId: 11,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 4,
  ),
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 2,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 3,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 4,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 5,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 6,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 7,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 8,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 9,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 10,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 11,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 8,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 9,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 10,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 11,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 9,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 10,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 4,
  ),
  const TeamModel(
    teamId: 11,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 4,
  ),
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 2,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 3,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 4,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 5,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 6,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 7,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 8,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 9,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 10,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 11,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 8,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 9,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 10,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 11,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 9,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 10,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 4,
  ),
  const TeamModel(
    teamId: 11,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 4,
  ),
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 2,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 3,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 4,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 5,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 6,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 7,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 8,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 9,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 10,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 11,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 8,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 9,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 10,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 11,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 9,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 10,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 4,
  ),
  const TeamModel(
    teamId: 11,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 4,
  ),
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 2,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 3,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 4,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 5,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 6,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 1,
  ),
  const TeamModel(
    teamId: 7,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 8,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 9,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 10,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 11,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 2,
  ),
  const TeamModel(
    teamId: 8,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 9,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 10,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 11,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 1,
    teamName: "Team 1",
    leagueName: "League 1",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 25,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 9,
    teamName: "Team 2",
    leagueName: "League 2",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 13,
    leagueId: 3,
  ),
  const TeamModel(
    teamId: 10,
    teamName: "Team 3",
    leagueName: "League 3",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 30,
    leagueId: 4,
  ),
  const TeamModel(
    teamId: 11,
    teamName: "Team 4",
    leagueName: "League 4",
    gamesPlayed: 15,
    goalsScored: 25,
    goalsConceded: 10,
    points: 10,
    leagueId: 4,
  ),
];

final DUMMY_LEAGUES = [
  LeagueModel(
    leagueId: 1,
    leagueName: 'League 1',
    leagueRegionName: 'Südbaden',
    numberOfTeams: 17,
    teams: DUMMY_TEAMS,
  ),
  LeagueModel(
    leagueId: 2,
    leagueName: 'League 2',
    leagueRegionName: 'Bayern',
    numberOfTeams: 16,
    teams: DUMMY_TEAMS,
  ),
  LeagueModel(
    leagueId: 3,
    leagueName: 'League 3',
    leagueRegionName: 'Baden',
    numberOfTeams: 17,
    teams: DUMMY_TEAMS,
  ),
  LeagueModel(
    leagueId: 4,
    leagueName: 'League 4',
    leagueRegionName: 'Würrtemberg',
    numberOfTeams: 21,
    teams: DUMMY_TEAMS,
  ),
];
